Review
shpikich/KickSharing pull request #1
Opened 2021-09-13 18:14 UTC by shpikich

2021-09-13 19:43 UTC, AlexAntufiev requested changes

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/controller/UserController.java
> +    public ResponseEntity<List<User>> findLastFiveUsers() {
лучше findLastUsers, чтобы не менять название, когда надо будет найти последних 6 или другое число

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/controller/KickScooterController.java
> +    public ResponseEntity<String> deleteKickScooter(@PathVariable(value = "kickscooter_id") Long kickScooterId) {
следуя твоему неймингу kick_scooter_id

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterService.java
> +    List<KickScooter> displayListOfAllKickScooters();
когда ты что-то загружаешь, то у тебя выбор между get find fetch и тд, display - наверно вообще не используют)
get и fetch возвращают не null сущность
find может вернуть null

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterService.java
> +    List<KickScooter> displayListOfFreeKickScooters();
два похожих метода, но возвращают скутеры с разными статусами - может как-то можно в один метод запихнуть?)

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        kickScooterRepository.findAll();
расскажи про этот метод, не очень понял
1. Ты передаешь скутеры и сохраняешь их - ок
2. Пробегаешь по сохраненным и обновляешь поля статуса - почему не сделать в п. 1 ?
3. Зачем еще искать все скутеры? видимо забыл удалить

итого у тебя 1 + количество_скутеров запросов в базу данных, лучше сделать 1, так как база данных самый важный компонент твоей системы - навернется и пользователи будут негодовать

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        throw new NoSuchElementException("KickScooter with this id wasn't found");
в исключение нужно пробросить kickScooterId

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +            optionalKickScooter.get();
это лишнее

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        Optional<KickScooter> optionalKickScooter = kickScooterRepository.findById(kickScooterId);
понял суть optional?

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +    public User rentKickScooter(Long userId, List<KickScooter> kickScooters) {
один из вопрос на собеседовании у тебя будет про асимптотическую сложность алгоритма ( O большое ) 
O(n) O(1) O(n2) O(log n)
вопросы:
1. На какой вопрос позволяет ответить  асимптотическая сложность ?
2. Попробуй оценить сложность этого алгоритма

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +        throw new NoSuchElementException("User with this id wasn't found");
прокинуть userId

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +            throw new IllegalArgumentException("User must be over 18 years old");
userId

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +                } else throw new NoSuchElementException("KickScooter with this name wasn't found");
userId + почему name ?

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +                List<KickScooter> listOfRentedKickScooters = new ArrayList<>(user.getKickScooters());
user.getKickScooters() итак возвращается список же? зачем в еще один заворачивать ?

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +                        if (kickScooter.getName().equals(requestedKickScooterName.getName())) {
почему по имени, а не по айди идет сравнение?

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +                                    .withStatus(RENTED)
для таких моментов впринципе можно пользоваться сеттером, но можно и так

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +                    throw new NoSuchElementException("KickScooter with this id wasn't found");
userId

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +            throw new NoSuchElementException("User with this id wasn't found");
userId

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +                if (optionalKickScooter.isPresent()) {
есть прикольный метод .orElseThrow() который тебе позволит взять скутер, если он есть, или кинуть исключение, если его нет

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/UserServiceImpl.java
> +        throw new NoSuchElementException("User with this id wasn't found");
userId

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/UserServiceImpl.java
> +        throw new NoSuchElementException("User with this id wasn't found");
userId

2021-09-13 19:43 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/UserServiceImpl.java
> +        LinkedList<User> userList = new LinkedList<>((List<User>) userRepository.findAll());
зачем еще один список создавать?

2021-09-13 19:43 UTC, AlexAntufiev commented on src/test/java/ru/yushkov/kicksharing/controller/UserControllerTest.java
> +    void shouldCreateUser() throws Exception {
давай еще на изменение возраста?

2021-09-15 10:42 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        kickScooterRepository.findAll();
@Override
    public List<KickScooter> addKickScooters(List<KickScooter> kickScooters) {
        List<KickScooter> addedKickScooters = new ArrayList<>();
        for (KickScooter kickScooter : kickScooters) {
            KickScooter kickScooterWithStatus = new KickScooter.Builder()
                    .withName(kickScooter.getName())
                    .withStatus(AVAILABLE)
                    .withId(kickScooter.getKickScooterId())
                    .build();
            addedKickScooters.add(kickScooterWithStatus);
        }
        return (List<KickScooter>) kickScooterRepository.saveAll(addedKickScooters);
    }

2021-09-15 10:48 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        kickScooterRepository.findAll();
@Override
    public List<KickScooter> addKickScooters(List<KickScooter> kickScooters) {
        List<KickScooter> addedKickScooters = new ArrayList<>();
        for (KickScooter kickScooter : kickScooters) {
            KickScooter kickScooterWithStatus = new KickScooter.Builder()
                    .withName(kickScooter.getName())
                    .withStatus(AVAILABLE)
                    .withId(kickScooter.getKickScooterId())
                    .build();
            addedKickScooters.add(kickScooterWithStatus);
        }
        return (List<KickScooter>) kickScooterRepository.saveAll(addedKickScooters);
    }

2021-09-15 10:52 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        kickScooterRepository.findAll();
Переписал так, чтобы был всего один запрос в БД

2021-09-15 12:18 UTC, shpikich commented on src/test/java/ru/yushkov/kicksharing/controller/UserControllerTest.java
> +    void shouldCreateUser() throws Exception {
Добавил
```suggestion
    void shouldCreateUser() throws Exception {
```

2021-09-15 12:20 UTC, shpikich commented on src/test/java/ru/yushkov/kicksharing/controller/UserControllerTest.java
> +    void shouldCreateUser() throws Exception {
```suggestion
        @Test
    void shouldUpdateUserAge() throws Exception {
        User user = new User.Builder()
                .withName("Ivan")
                .withSurname("Ivanov")
                .withAge(25)
                .build();

        userService.addUser(user);

        this.mvc.perform(put("/users/{user_id}", 1)
                        .param("age", "55")
                        .contentType(MediaType.APPLICATION_JSON_VALUE))
                .andDo(print())
                .andExpect(status().isAccepted())
                .andExpect(jsonPath("$.name").value("Ivan"))
                .andExpect(jsonPath("$.surname").value("Ivanov"))
                .andExpect(jsonPath("$.age").value(55))
                .andExpect(jsonPath("$.userId").value(1));
    }
```

2021-09-15 12:20 UTC, shpikich commented on src/test/java/ru/yushkov/kicksharing/controller/UserControllerTest.java
> +    void shouldCreateUser() throws Exception {
Добавил

2021-09-15 16:38 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/UserServiceImpl.java
> +        LinkedList<User> userList = new LinkedList<>((List<User>) userRepository.findAll());
> зачем еще один список создавать?
ыфвфыв

2021-09-15 16:44 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/UserServiceImpl.java
> +        LinkedList<User> userList = new LinkedList<>((List<User>) userRepository.findAll());
lastFiveUsers для сохранения последних пользователей, который возвращается в методе, а userList для извлечения последнего не удаленного пользователя

2021-09-15 16:45 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/UserServiceImpl.java
> +        LinkedList<User> userList = new LinkedList<>((List<User>) userRepository.findAll());
public List<User> findLastUsers() {
        List<User> lastUsers = new ArrayList<>();
        LinkedList<User> userList = new LinkedList<>((List<User>) userRepository.findAll());
        if (userList.size() != 0) {
            Long lastUserIndex = userList.getLast().getUserId();
            do {
                Optional<User> optionalUser = userRepository.findById(lastUserIndex);
                optionalUser.ifPresent(lastUsers::add);
                lastUserIndex--;
            } while (lastUsers.size() != numberOfDisplayedUsers);
            return lastUsers;
        }
        throw new NoSuchElementException("There are no users in the database!");
    }

2021-09-15 16:53 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +                        if (kickScooter.getName().equals(requestedKickScooterName.getName())) {
Я подумал, что если пользователь арендует самокат, он может передать только имя, у него нет информации о том, какой у самоката ID

2021-09-15 17:17 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +                List<KickScooter> listOfRentedKickScooters = new ArrayList<>(user.getKickScooters());
Оборачивание в еще один список я добавил для того, чтобы если пользователь решил доарендовать новые самокаты, добавить их в эту обертку 

    listOfRentedKickScooters.add(rentedKickScooter);
а потом сравнить с количеством самокатов, которые к нему и так привязаны были, и если значения не сходятся, то пользователь пересохраняется с новым количеством самокатов

    if (user.getKickScooters().size() != listOfRentedKickScooters.size()) {

2021-09-15 19:14 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +                        if (kickScooter.getName().equals(requestedKickScooterName.getName())) {
пользователь у себя в приложении кликает по имени, но твое приложение тебе на сервер присылает айди
ну это деталь, можно это опустить

2021-09-15 19:39 UTC, AlexAntufiev requested changes

2021-09-15 19:39 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        if (status.equals("all")) {
у enum можно добавить поле с конструктором, в котором будет содержаться как раз этот код, чтобы не хардкодить как у тебя здесь

2021-09-15 19:39 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/controller/KickScooterController.java
> -    }
этот метод можно было оставить, но вызывать kickScooterService.getListOfKickScooters(All), как хочешь)

2021-09-16 08:59 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        if (status.equals("all")) {
@AlexAntufiev тут не очень понял. Просто у enum Status два значения только: RENTED и AVAILABLE. А в качестве параметра передается строка и если all - выводятся все самокаты, а если available - только доступные для аренды

2021-09-16 20:20 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/UserServiceImpl.java
> +        LinkedList<User> userList = new LinkedList<>((List<User>) userRepository.findAll());
@Override
    public List<User> findLastUsers() {
        List<User> lastUsers = new ArrayList<>();
        LinkedList<User> userList = new LinkedList<>((List<User>) userRepository.findAll());
        if (userList.size() != 0) {
            Long lastUserIndex = userList.getLast().getUserId();
            do {
                Optional<User> optionalUser = userRepository.findById(lastUserIndex);
                if (optionalUser.isPresent()) {
                    lastUsers.add(optionalUser.get());
                }
                lastUserIndex--;
            } while (lastUsers.size() != numberOfDisplayedUsers);
            return lastUsers;
        }
        throw new NoSuchElementException("There are no users in the database!");
    }

2021-09-16 21:32 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        if (status.equals("all")) {
да, все так

можно сделать так
```
enum class Status {

AVAILABLE("AVAILABLE"), 
RENTED("RENTED"),
;

private final String code;

Status(String code) {
this.code = code;
}

}
```
и тогда можно сравнивать с их кодом, без хардкора

2021-09-17 06:28 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        if (status.equals("all")) {
@AlexAntufiev Тогда я могу строку в коде
        
    } else if (status.equals("available")) {
Заменить на эту строку, если еще геттер в enum добавлю

        } else if (status.equals(AVAILABLE.getCode())) {

А как в этой строчке от хардкода избавиться, если у меня URL localhost:8080/kickscooters?status=all, я не понимаю
    
    if (status.equals("all")) {

2021-09-17 06:53 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        if (status.equals("all")) {
All - ввести статус ещё такой или просто для него проверять все остальные статусы

2021-09-17 06:53 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/KickScooterServiceImpl.java
> +        if (status.equals("all")) {
А так все правильно написал

2021-09-18 09:45 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +    public User rentKickScooter(Long userId, List<KickScooter> kickScooters) {
1. Ассимптотическая сложность алгоритма позволяет ответить на вопрос, как быстро увеличивается время работы алгоритма с увеличением объёма данных, по какой функции

2021-09-18 09:46 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +    public User rentKickScooter(Long userId, List<KickScooter> kickScooters) {
@Override
    public User rentKickScooter(Long userId, List<KickScooter> kickScooters) {
        Optional<User> optionalUser = userRepository.findById(userId);
        if (optionalUser.isPresent()) {
            User user = optionalUser.get();
            int userKickScooters = user.getKickScooters().size();
            if (kickScooters.size() + userKickScooters <= maximumNumberOfScooters) {
                if (user.getAge() >= minimumUserAge) {
                    List<KickScooter> listOfRentedKickScooters = new ArrayList<>(user.getKickScooters());
                    for (KickScooter requestedKickScooterName : kickScooters) {
                        List<KickScooter> allKickScooters = (List<KickScooter>) kickScooterRepository.findAll();
                        for (KickScooter kickScooter : allKickScooters) {
                            if (kickScooter.getName().equals(requestedKickScooterName.getName())) {
                                KickScooter rentedKickScooter = new KickScooter.Builder()
                                        .withName(kickScooter.getName())
                                        .withStatus(RENTED)
                                        .withId(kickScooter.getKickScooterId())
                                        .build();
                                kickScooterRepository.save(rentedKickScooter);
                                listOfRentedKickScooters.add(rentedKickScooter);
                            }
                        }
                    }
                    if (userKickScooters != listOfRentedKickScooters.size()) {
                        User updatedUser = new User.Builder()
                                .withName(user.getName())
                                .withSurname(user.getSurname())
                                .withAge(user.getAge())
                                .withKickScooters(listOfRentedKickScooters)
                                .withId(user.getUserId())
                                .build();
                        userRepository.save(updatedUser);
                        return updatedUser;
                    } else throw new NoSuchElementException("KickScooters with this names wasn't found");
                }
                throw new IllegalArgumentException("User with id " + userId + " must be over 18 years old");
            }
            throw new IllegalArgumentException("User can't rent more than 5 kickScooters");
        }
        throw new NoSuchElementException("User with id " + userId + " wasn't found");
    }

2021-09-18 09:55 UTC, shpikich commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +    public User rentKickScooter(Long userId, List<KickScooter> kickScooters) {
@AlexAntufiev переписал немного метод, добавив проверку на количество арендуемых скутеров, потому что у меня по условию пользователь может арендовать не более 5 скутеров за раз. В связи с этим я думаю, что:
2.  Ассимптотическая сложность данного алгоритма O(n), где n - allKickScooters во вложенном for. Внешний for не учитывал, потому что он не больше 5, откинул как константу

2021-09-18 11:52 UTC, AlexAntufiev approved these changes
good job!

2021-09-18 22:53 UTC, AlexAntufiev commented on src/main/java/ru/yushkov/kicksharing/service/RentServiceImpl.java
> +    public User rentKickScooter(Long userId, List<KickScooter> kickScooters) {
все правильно

2022-02-05 09:53 UTC, closed without merging